#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace VirtualSummit.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }
	}
}

























namespace VirtualSummit.Models.sitecore.templates.VirtualSummit.Base
{


 	/// <summary>
	/// IPageTitles Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Base/PageTitles</para>	
	/// <para>ID: 81d9fecd-bee1-4670-8a3e-86dc3c78275c</para>	
	/// </summary>
	[SitecoreType(TemplateId=PageTitles.TemplateIdString)]
	public partial interface IPageTitles : IGlassBase 
	{

		/// <summary>
		/// The FeatureTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: a15681ee-a3fb-43ad-a850-74ce0bb7ec43</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(PageTitles.FeatureTitleFieldName)]
		string FeatureTitle  {get; set;}
			

		/// <summary>
		/// The LongTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ac5dfc10-6213-4783-9c40-f6a2785da62d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(PageTitles.LongTitleFieldName)]
		string LongTitle  {get; set;}
			

		/// <summary>
		/// The ShortTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 542a4bce-8211-4b97-8ec9-6d201d5f2af1</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(PageTitles.ShortTitleFieldName)]
		string ShortTitle  {get; set;}
			

	}

	
	/// <summary>
	/// PageTitles
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Base/PageTitles</para>	
	/// <para>ID: 81d9fecd-bee1-4670-8a3e-86dc3c78275c</para>	
	/// </summary>
	[SitecoreType(TemplateId=PageTitles.TemplateIdString)]
	public partial class PageTitles  : GlassBase, IPageTitles 
	{
	    
		public const string TemplateIdString = "81d9fecd-bee1-4670-8a3e-86dc3c78275c";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "PageTitles";


		/// <summary>
		/// The FeatureTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: a15681ee-a3fb-43ad-a850-74ce0bb7ec43</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(PageTitles.FeatureTitleFieldName)]
		public virtual string FeatureTitle  {get; set;}

		public static readonly ID FeatureTitleFieldId = new ID("a15681ee-a3fb-43ad-a850-74ce0bb7ec43");
		public const string FeatureTitleFieldName = "FeatureTitle";
			

		/// <summary>
		/// The LongTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ac5dfc10-6213-4783-9c40-f6a2785da62d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(PageTitles.LongTitleFieldName)]
		public virtual string LongTitle  {get; set;}

		public static readonly ID LongTitleFieldId = new ID("ac5dfc10-6213-4783-9c40-f6a2785da62d");
		public const string LongTitleFieldName = "LongTitle";
			

		/// <summary>
		/// The ShortTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 542a4bce-8211-4b97-8ec9-6d201d5f2af1</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(PageTitles.ShortTitleFieldName)]
		public virtual string ShortTitle  {get; set;}

		public static readonly ID ShortTitleFieldId = new ID("542a4bce-8211-4b97-8ec9-6d201d5f2af1");
		public const string ShortTitleFieldName = "ShortTitle";
			
	
	}

}

