





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;


namespace VirtualSummit.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }
	}
}









namespace VirtualSummit.Models.sitecore.templates.VirtualSummit.Pages
{


 	/// <summary>
	/// IGeneral Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Pages/General</para>	
	/// <para>ID: 23c9097e-8411-46bb-88ec-d93ce6028ffc</para>	
	/// </summary>
	[SitecoreType(TemplateId=General.TemplateIdString)]
	public partial interface IGeneral : IGlassBase , global::VirtualSummit.Models.sitecore.templates.VirtualSummit.Base.IPageTitles, global::VirtualSummit.Models.sitecore.templates.VirtualSummit.Base.IContent
	{
	}

	
	/// <summary>
	/// General
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Pages/General</para>	
	/// <para>ID: 23c9097e-8411-46bb-88ec-d93ce6028ffc</para>	
	/// </summary>
	[SitecoreType(TemplateId=General.TemplateIdString)]
	public partial class General  : GlassBase, IGeneral 
	{
	    
		public const string TemplateIdString = "23c9097e-8411-46bb-88ec-d93ce6028ffc";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "General";

		/// <summary>
		/// The FeatureTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae259d53-8cc5-4902-9201-38758d5b785b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(General.FeatureTitleFieldName)]
		public virtual string FeatureTitle  {get; set;}

		public static readonly ID FeatureTitleFieldId = new ID("ae259d53-8cc5-4902-9201-38758d5b785b");
		public const string FeatureTitleFieldName = "FeatureTitle";
			
		/// <summary>
		/// The LongTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 8e22728b-0844-411d-bc83-89dcca32e624</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(General.LongTitleFieldName)]
		public virtual string LongTitle  {get; set;}

		public static readonly ID LongTitleFieldId = new ID("8e22728b-0844-411d-bc83-89dcca32e624");
		public const string LongTitleFieldName = "LongTitle";
			
		/// <summary>
		/// The ShortTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae6456c8-5766-46a4-9dc2-d1619b645432</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(General.ShortTitleFieldName)]
		public virtual string ShortTitle  {get; set;}

		public static readonly ID ShortTitleFieldId = new ID("ae6456c8-5766-46a4-9dc2-d1619b645432");
		public const string ShortTitleFieldName = "ShortTitle";
			
		/// <summary>
		/// The Body field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: bf7e7ff5-33d8-4d3a-86c3-673775ed02a0</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(General.BodyFieldName)]
		public virtual string Body  {get; set;}

		public static readonly ID BodyFieldId = new ID("bf7e7ff5-33d8-4d3a-86c3-673775ed02a0");
		public const string BodyFieldName = "Body";
			
	
	}
}











namespace VirtualSummit.Models.sitecore.templates.VirtualSummit.Pages
{


 	/// <summary>
	/// INewsArticle Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Pages/NewsArticle</para>	
	/// <para>ID: 24f5866e-0b1a-4c18-93b1-1b331de47d5d</para>	
	/// </summary>
	[SitecoreType(TemplateId=NewsArticle.TemplateIdString)]
	public partial interface INewsArticle : IGlassBase , global::VirtualSummit.Models.sitecore.templates.VirtualSummit.Base.IPageTitles, global::VirtualSummit.Models.sitecore.templates.VirtualSummit.Base.IContent
	{
		/// <summary>
		/// The Date field.
		/// <para></para>
		/// <para>Field Type: Date</para>		
		/// <para>Field ID: 3a166ade-21fe-4c91-a5b6-7181f0d4513d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(NewsArticle.DateFieldName)]
		DateTime Date  {get; set;}
			
		/// <summary>
		/// The Featured field.
		/// <para></para>
		/// <para>Field Type: Checkbox</para>		
		/// <para>Field ID: 26ba8e78-d5c8-4305-b8cf-0e6ebdf2e32b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(NewsArticle.FeaturedFieldName)]
		bool Featured  {get; set;}
			
	}

	
	/// <summary>
	/// NewsArticle
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Pages/NewsArticle</para>	
	/// <para>ID: 24f5866e-0b1a-4c18-93b1-1b331de47d5d</para>	
	/// </summary>
	[SitecoreType(TemplateId=NewsArticle.TemplateIdString)]
	public partial class NewsArticle  : GlassBase, INewsArticle 
	{
	    
		public const string TemplateIdString = "24f5866e-0b1a-4c18-93b1-1b331de47d5d";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "NewsArticle";

		/// <summary>
		/// The Date field.
		/// <para></para>
		/// <para>Field Type: Date</para>		
		/// <para>Field ID: 3a166ade-21fe-4c91-a5b6-7181f0d4513d</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(NewsArticle.DateFieldName)]
		public virtual DateTime Date  {get; set;}

		public static readonly ID DateFieldId = new ID("3a166ade-21fe-4c91-a5b6-7181f0d4513d");
		public const string DateFieldName = "Date";
			
		/// <summary>
		/// The Featured field.
		/// <para></para>
		/// <para>Field Type: Checkbox</para>		
		/// <para>Field ID: 26ba8e78-d5c8-4305-b8cf-0e6ebdf2e32b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(NewsArticle.FeaturedFieldName)]
		public virtual bool Featured  {get; set;}

		public static readonly ID FeaturedFieldId = new ID("26ba8e78-d5c8-4305-b8cf-0e6ebdf2e32b");
		public const string FeaturedFieldName = "Featured";
			
		/// <summary>
		/// The FeatureTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae259d53-8cc5-4902-9201-38758d5b785b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(NewsArticle.FeatureTitleFieldName)]
		public virtual string FeatureTitle  {get; set;}

		public static readonly ID FeatureTitleFieldId = new ID("ae259d53-8cc5-4902-9201-38758d5b785b");
		public const string FeatureTitleFieldName = "FeatureTitle";
			
		/// <summary>
		/// The LongTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 8e22728b-0844-411d-bc83-89dcca32e624</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(NewsArticle.LongTitleFieldName)]
		public virtual string LongTitle  {get; set;}

		public static readonly ID LongTitleFieldId = new ID("8e22728b-0844-411d-bc83-89dcca32e624");
		public const string LongTitleFieldName = "LongTitle";
			
		/// <summary>
		/// The ShortTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae6456c8-5766-46a4-9dc2-d1619b645432</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(NewsArticle.ShortTitleFieldName)]
		public virtual string ShortTitle  {get; set;}

		public static readonly ID ShortTitleFieldId = new ID("ae6456c8-5766-46a4-9dc2-d1619b645432");
		public const string ShortTitleFieldName = "ShortTitle";
			
		/// <summary>
		/// The Body field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: bf7e7ff5-33d8-4d3a-86c3-673775ed02a0</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(NewsArticle.BodyFieldName)]
		public virtual string Body  {get; set;}

		public static readonly ID BodyFieldId = new ID("bf7e7ff5-33d8-4d3a-86c3-673775ed02a0");
		public const string BodyFieldName = "Body";
			
	
	}
}











namespace VirtualSummit.Models.sitecore.templates.VirtualSummit.Pages
{


 	/// <summary>
	/// IFeaturedNews Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Pages/FeaturedNews</para>	
	/// <para>ID: 29baffc1-9473-43de-a8d7-f2a7fa523a40</para>	
	/// </summary>
	[SitecoreType(TemplateId=FeaturedNews.TemplateIdString)]
	public partial interface IFeaturedNews : IGlassBase , global::VirtualSummit.Models.sitecore.templates.VirtualSummit.Base.IPageTitles, global::VirtualSummit.Models.sitecore.templates.VirtualSummit.Base.IContent
	{
	}

	
	/// <summary>
	/// FeaturedNews
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Pages/FeaturedNews</para>	
	/// <para>ID: 29baffc1-9473-43de-a8d7-f2a7fa523a40</para>	
	/// </summary>
	[SitecoreType(TemplateId=FeaturedNews.TemplateIdString)]
	public partial class FeaturedNews  : GlassBase, IFeaturedNews 
	{
	    
		public const string TemplateIdString = "29baffc1-9473-43de-a8d7-f2a7fa523a40";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "FeaturedNews";

		/// <summary>
		/// The FeatureTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae259d53-8cc5-4902-9201-38758d5b785b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(FeaturedNews.FeatureTitleFieldName)]
		public virtual string FeatureTitle  {get; set;}

		public static readonly ID FeatureTitleFieldId = new ID("ae259d53-8cc5-4902-9201-38758d5b785b");
		public const string FeatureTitleFieldName = "FeatureTitle";
			
		/// <summary>
		/// The LongTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 8e22728b-0844-411d-bc83-89dcca32e624</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(FeaturedNews.LongTitleFieldName)]
		public virtual string LongTitle  {get; set;}

		public static readonly ID LongTitleFieldId = new ID("8e22728b-0844-411d-bc83-89dcca32e624");
		public const string LongTitleFieldName = "LongTitle";
			
		/// <summary>
		/// The ShortTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae6456c8-5766-46a4-9dc2-d1619b645432</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(FeaturedNews.ShortTitleFieldName)]
		public virtual string ShortTitle  {get; set;}

		public static readonly ID ShortTitleFieldId = new ID("ae6456c8-5766-46a4-9dc2-d1619b645432");
		public const string ShortTitleFieldName = "ShortTitle";
			
		/// <summary>
		/// The Body field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: bf7e7ff5-33d8-4d3a-86c3-673775ed02a0</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(FeaturedNews.BodyFieldName)]
		public virtual string Body  {get; set;}

		public static readonly ID BodyFieldId = new ID("bf7e7ff5-33d8-4d3a-86c3-673775ed02a0");
		public const string BodyFieldName = "Body";
			
	
	}
}











namespace VirtualSummit.Models.sitecore.templates.VirtualSummit.Settings
{


 	/// <summary>
	/// ITwitterSettings Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Settings/TwitterSettings</para>	
	/// <para>ID: 32afc3d4-3b42-4b42-a681-cf1581ff89d3</para>	
	/// </summary>
	[SitecoreType(TemplateId=TwitterSettings.TemplateIdString)]
	public partial interface ITwitterSettings : IGlassBase 
	{
		/// <summary>
		/// The AccessToken field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: a0a1cd5f-d1fa-4b3b-9251-dac1a9636d58</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(TwitterSettings.AccessTokenFieldName)]
		string AccessToken  {get; set;}
			
		/// <summary>
		/// The AccessTokenSecret field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 38ab8a6a-c8c5-4217-af3a-eccdcf11a555</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(TwitterSettings.AccessTokenSecretFieldName)]
		string AccessTokenSecret  {get; set;}
			
		/// <summary>
		/// The ConsumerKey field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 88a8699c-fcd9-45aa-9364-3d6f391a35e6</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(TwitterSettings.ConsumerKeyFieldName)]
		string ConsumerKey  {get; set;}
			
		/// <summary>
		/// The ConsumerSecret field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 747eb247-5d0e-448b-bea1-a500b0debd26</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(TwitterSettings.ConsumerSecretFieldName)]
		string ConsumerSecret  {get; set;}
			
	}

	
	/// <summary>
	/// TwitterSettings
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Settings/TwitterSettings</para>	
	/// <para>ID: 32afc3d4-3b42-4b42-a681-cf1581ff89d3</para>	
	/// </summary>
	[SitecoreType(TemplateId=TwitterSettings.TemplateIdString)]
	public partial class TwitterSettings  : GlassBase, ITwitterSettings 
	{
	    
		public const string TemplateIdString = "32afc3d4-3b42-4b42-a681-cf1581ff89d3";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "TwitterSettings";

		/// <summary>
		/// The AccessToken field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: a0a1cd5f-d1fa-4b3b-9251-dac1a9636d58</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(TwitterSettings.AccessTokenFieldName)]
		public virtual string AccessToken  {get; set;}

		public static readonly ID AccessTokenFieldId = new ID("a0a1cd5f-d1fa-4b3b-9251-dac1a9636d58");
		public const string AccessTokenFieldName = "AccessToken";
			
		/// <summary>
		/// The AccessTokenSecret field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 38ab8a6a-c8c5-4217-af3a-eccdcf11a555</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(TwitterSettings.AccessTokenSecretFieldName)]
		public virtual string AccessTokenSecret  {get; set;}

		public static readonly ID AccessTokenSecretFieldId = new ID("38ab8a6a-c8c5-4217-af3a-eccdcf11a555");
		public const string AccessTokenSecretFieldName = "AccessTokenSecret";
			
		/// <summary>
		/// The ConsumerKey field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 88a8699c-fcd9-45aa-9364-3d6f391a35e6</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(TwitterSettings.ConsumerKeyFieldName)]
		public virtual string ConsumerKey  {get; set;}

		public static readonly ID ConsumerKeyFieldId = new ID("88a8699c-fcd9-45aa-9364-3d6f391a35e6");
		public const string ConsumerKeyFieldName = "ConsumerKey";
			
		/// <summary>
		/// The ConsumerSecret field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 747eb247-5d0e-448b-bea1-a500b0debd26</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(TwitterSettings.ConsumerSecretFieldName)]
		public virtual string ConsumerSecret  {get; set;}

		public static readonly ID ConsumerSecretFieldId = new ID("747eb247-5d0e-448b-bea1-a500b0debd26");
		public const string ConsumerSecretFieldName = "ConsumerSecret";
			
	
	}
}











namespace VirtualSummit.Models.sitecore.templates.VirtualSummit.Base
{


 	/// <summary>
	/// IPageTitles Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Base/PageTitles</para>	
	/// <para>ID: 6b877eba-2aea-4fcb-aaa4-d18205640315</para>	
	/// </summary>
	[SitecoreType(TemplateId=PageTitles.TemplateIdString)]
	public partial interface IPageTitles : IGlassBase 
	{
		/// <summary>
		/// The FeatureTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae259d53-8cc5-4902-9201-38758d5b785b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(PageTitles.FeatureTitleFieldName)]
		string FeatureTitle  {get; set;}
			
		/// <summary>
		/// The LongTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 8e22728b-0844-411d-bc83-89dcca32e624</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(PageTitles.LongTitleFieldName)]
		string LongTitle  {get; set;}
			
		/// <summary>
		/// The ShortTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae6456c8-5766-46a4-9dc2-d1619b645432</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(PageTitles.ShortTitleFieldName)]
		string ShortTitle  {get; set;}
			
	}

	
	/// <summary>
	/// PageTitles
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Base/PageTitles</para>	
	/// <para>ID: 6b877eba-2aea-4fcb-aaa4-d18205640315</para>	
	/// </summary>
	[SitecoreType(TemplateId=PageTitles.TemplateIdString)]
	public partial class PageTitles  : GlassBase, IPageTitles 
	{
	    
		public const string TemplateIdString = "6b877eba-2aea-4fcb-aaa4-d18205640315";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "PageTitles";

		/// <summary>
		/// The FeatureTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae259d53-8cc5-4902-9201-38758d5b785b</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(PageTitles.FeatureTitleFieldName)]
		public virtual string FeatureTitle  {get; set;}

		public static readonly ID FeatureTitleFieldId = new ID("ae259d53-8cc5-4902-9201-38758d5b785b");
		public const string FeatureTitleFieldName = "FeatureTitle";
			
		/// <summary>
		/// The LongTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 8e22728b-0844-411d-bc83-89dcca32e624</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(PageTitles.LongTitleFieldName)]
		public virtual string LongTitle  {get; set;}

		public static readonly ID LongTitleFieldId = new ID("8e22728b-0844-411d-bc83-89dcca32e624");
		public const string LongTitleFieldName = "LongTitle";
			
		/// <summary>
		/// The ShortTitle field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: ae6456c8-5766-46a4-9dc2-d1619b645432</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(PageTitles.ShortTitleFieldName)]
		public virtual string ShortTitle  {get; set;}

		public static readonly ID ShortTitleFieldId = new ID("ae6456c8-5766-46a4-9dc2-d1619b645432");
		public const string ShortTitleFieldName = "ShortTitle";
			
	
	}
}











namespace VirtualSummit.Models.sitecore.templates.VirtualSummit.Base
{


 	/// <summary>
	/// IContent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Base/Content</para>	
	/// <para>ID: cd86dcd5-eac4-444b-9880-527fed43c4a7</para>	
	/// </summary>
	[SitecoreType(TemplateId=Content.TemplateIdString)]
	public partial interface IContent : IGlassBase 
	{
		/// <summary>
		/// The Body field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: bf7e7ff5-33d8-4d3a-86c3-673775ed02a0</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(Content.BodyFieldName)]
		string Body  {get; set;}
			
	}

	
	/// <summary>
	/// Content
	/// <para></para>
	/// <para>Path: /sitecore/templates/VirtualSummit/Base/Content</para>	
	/// <para>ID: cd86dcd5-eac4-444b-9880-527fed43c4a7</para>	
	/// </summary>
	[SitecoreType(TemplateId=Content.TemplateIdString)]
	public partial class Content  : GlassBase, IContent 
	{
	    
		public const string TemplateIdString = "cd86dcd5-eac4-444b-9880-527fed43c4a7";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Content";

		/// <summary>
		/// The Body field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: bf7e7ff5-33d8-4d3a-86c3-673775ed02a0</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(Content.BodyFieldName)]
		public virtual string Body  {get; set;}

		public static readonly ID BodyFieldId = new ID("bf7e7ff5-33d8-4d3a-86c3-673775ed02a0");
		public const string BodyFieldName = "Body";
			
	
	}
}

